WIP: feat: spellchecking API.
Blightmud/Blightmud pull request #736
Opened 2023-02-11 20:23 UTC by cpu

#### Description

This branch adds a new Lua module, `spellcheck`, with three functions:

* `spellcheck.init(aff_path, dict_path)` - initializes a spellchecker with the paths to a [Hunspell][0] compatible affix file and dictionary file. Must be called before any other spellcheck functions or an error will be thrown.
* `spellcheck.check(word) -> bool` - returns true if the word is in the dictionary that the spellchecker was initialized with. Errs if the spellchecker hasn't been initialized.
* `spellcheck.suggest(word) -> table` - if the given word is misspelled, returns a table array of suggested replacements in order of likelihood.

Presently these features are implemented with a backend that relies on the [`hunspell-rs` crate][1], which in turn uses [`hunspell-sys`][2] to interact with [libhunspell][0]. Hunspell is used extensively (e.g. by LibreOffice, Firefox) so compatible dictionaries/affix files are easy to source and the results are competitive with popular software. To avoid adding a new external dependency we use the "bundled" feature of `hunspell-sys` to have that crate bring along its own statically linked libhunspell. This means no changes are required for CI or the release process.

In the future the [`zspell`][3] crate looks like a promising pure Rust alternative to `hunspell-rs` that supports the Hunspell format and API. I elected not to use that crate for the short term because it doesn't yet have a stable API for providing suggestions and that's a core feature for a spellchecker. It should be possible to switch to this crate transparent to end users once it's feature complete.

For an example interactive spellchecker plugin built with this new Lua module, see [Blightspell][4].

Resolves #724.

[0]: http://hunspell.github.io/
[1]: https://crates.io/crates/hunspell-rs
[2]: https://crates.io/crates/hunspell-sys
[3]: https://crates.io/crates/zspell
[4]: https://github.com/cpu/blightspell

#### TODO

* [ ] - Test coverage
* [ ] - Review

#### Demo

Here's a quick recorded demo of Blightspell in action:

[![asciicast](https://asciinema.org/a/ZvMTNWBIOk1ib84isRUxrUHBu.svg)](https://asciinema.org/a/ZvMTNWBIOk1ib84isRUxrUHBu)

2023-02-13 14:43 UTC, LiquidityC commented on resources/help/spellcheck.md
> +
A minor extension of this intro that makes it clear that this module is **not** a fully fledged spellchecker.
Feel free to promote your own plugin here :wink: 

Something like:

> This module is not a complete spellchecking solution. It provides methods for checking the spelling of a word and finding spelling suggestions for a particular word for use within scripts.
> For a more complete spellchecker there are plugins available. Such as:
>
> - Your solution with link

2023-02-13 14:44 UTC, LiquidityC commented on resources/help/spellcheck.md
> +
Add:
- Returns true if the spelling is correct otherwise false

2023-02-13 14:45 UTC, LiquidityC commented on resources/help/spellcheck.md
> +- `table`   An array consisting of candidate replacement words, in
Change this last list entry into this format:
> Returns a bla bla bla...

2023-02-13 14:53 UTC, LiquidityC requested changes

2023-02-13 14:53 UTC, LiquidityC commented on src/lua/spellcheck.rs
> +            return Err(anyhow!("spellchecker not initialized"));
Change to `Err(anyhow!("spellchecker not initialized"))`

You can put the `Ok(())` in an else block or use the `match` pattern.

2023-02-13 17:22 UTC, cpu commented
@LiquidityC I integrated your feedback, added unit test coverage, and marked the PR ready for review. Let me know if I can do anything else.

2023-02-14 08:12 UTC, LiquidityC approved these changes

2023-02-14 08:13 UTC, merged