feat: add echo_input setting.
Blightmud/Blightmud pull request #807
Opened 2023-05-06 02:10 UTC by cpu

Previously all `ServerInput` events unconditionally called `screen.print_send` to echo input sent by a user to the screen. In the split screen mode this results in the input appearing with a `> ` prefix and special colouring. That's a sensible default but I would be happy to rely on the input buffer history for remembering what I sent and save some output screen space by not echoing all my input.

This commit adds a `echo_input` setting that can be changed to disable screen input echo behaviour on an opt-in basis.

The setting defaults to true, and can be changed at runtime with immediate effect. When set to false input is still logged but will no longer appear on the screen with a `> ` prefix. Setting it to true will restore the echo effect.

2023-05-08 07:27 UTC, LiquidityC commented
This one looks fine but it will break `ctrl - pgup/pgdn` behavior (see https://github.com/Blightmud/Blightmud/blob/dev/resources/help/search.md).
So make a note of that in the help text please.
Since I think it's a feature that often goes overlooked perhaps you could add the info about `ctrl - pgup/pgdn` in `scrolling.md` within this PR since you're laready fiddling with it?

2023-05-08 07:29 UTC, LiquidityC requested changes
See my comment in the PR.

2023-05-10 01:12 UTC, cpu commented
> This one looks fine but it will break ctrl - pgup/pgdn behavior (see [search.md](https://github.com/Blightmud/Blightmud/blob/dev/resources/help/search.md)).
> So make a note of that in the help text please.

Good catch, thank you. I've updated the `/help search` text. I also patched the Lua `search` module so `search.find_next_input` and `search.find_last_input` will print an error message if `echo_input` is disabled.

> Since I think it's a feature that often goes overlooked perhaps you could add the info about ctrl - pgup/pgdn in scrolling.md within this PR since you're laready fiddling with it?

Done.

2023-05-10 06:36 UTC, LiquidityC approved these changes
Nice work. Thanks

2023-05-10 06:36 UTC, merged